/*
 * generated by Xtext 2.10.0
 */
package esir3.im.ui;

import com.google.inject.Injector;
import esir3.im.tw.ui.internal.TwActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TwExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TwActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TwActivator.getInstance().getInjector(TwActivator.ESIR3_IM_TW);
	}
	
}
