/*
 * generated by Xtext 2.10.0
 */
package esir3.im.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTwScopeProvider extends DelegatingScopeProvider {
}
