/**
 * generated by Xtext 2.10.0
 */
package esir3.im;

import esir3.im.AbstractTwRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TwRuntimeModule extends AbstractTwRuntimeModule {
}
