/**
 * generated by Xtext 2.10.0
 */
package esir3.im;

import esir3.im.TwStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TwStandaloneSetup extends TwStandaloneSetupGenerated {
  public static void doSetup() {
    TwStandaloneSetup _twStandaloneSetup = new TwStandaloneSetup();
    _twStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
