/**
 * generated by Xtext 2.10.0
 */
package esir3.im.ui.contentassist;

import esir3.im.ui.contentassist.AbstractTwProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TwProposalProvider extends AbstractTwProposalProvider {
}
