/**
 * generated by Xtext 2.10.0
 */
package esir3.im.validation;

import esir3.im.validation.AbstractTwValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TwValidator extends AbstractTwValidator {
}
