/*
 * generated by Xtext 2.10.0
 */
package esir3.im.ui.tests;

import com.google.inject.Injector;
import esir3.im.tw.ui.internal.TwActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class TwUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TwActivator.getInstance().getInjector("esir3.im.Tw");
	}

}
