/**
 * generated by Xtext 2.10.0
 */
package esir3.im.ui;

import esir3.im.ui.AbstractTwUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TwUiModule extends AbstractTwUiModule {
  public TwUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
