/**
 * generated by Xtext 2.10.0
 */
package esir3.im.scoping;

import esir3.im.scoping.AbstractTwScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TwScopeProvider extends AbstractTwScopeProvider {
}
